version: '3.8'
services:
  nginx:
    container_name: nginx
    platform: linux/x86_64
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../laravel:/var/www/html
      - ./nginx/:/etc/nginx/conf.d/
    networks:
      - laravel-network
  laravel:
    container_name: laravel
    working_dir: /var/www/html
    build:
      args:
        USER: www-data
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ../laravel:/var/www/html
      - ./laravel.ini:/usr/local/etc/php/conf.d/laravel.ini
      - ./cacert.pem:/usr/local/etc/php/conf.d/cacert.pem
    networks:
      - laravel-network
  database:
    container_name: database
    image: mysql:latest
    restart: unless-stopped
    command: --init-file /data/application/init.sql
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: 123test321
      MYSQL_ROOT_PASSWORD: 123test321
    volumes:
      - ./mysql/init_db.sql:/data/application/init.sql
    networks:
      - laravel-network
  maildev:
    image: maildev/maildev
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    ports:
      - "1080:1080"
      - "1025:1025"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
    networks:
      - laravel-network
  redis:
    image: redis:latest
    container_name: redis_container
    environment:
      - REDIS_CLIENT=phpredis
      - REDIS_HOST=127.0.0.1
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
    ports:
      - "6379:6379"
    volumes:
      - ./redisdata:/data
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    tty: true
    stdin_open: true
    networks:
      - laravel-network
  queue:
   container_name: laravel_queue
   working_dir: /var/www/html
   build:
    args:
      USER: www-data
    context: ./
    dockerfile: Dockerfile
   restart: unless-stopped
   command: php artisan queue:listen
   volumes:
    - ../laravel:/var/www/html
    - ./laravel.ini:/usr/local/etc/php/conf.d/laravel.ini
   depends_on:
    - redis
    - database
   networks:
    - laravel-network
  scheduler:
    container_name: laravel_scheduler
    working_dir: /var/www/html
    build:
      args:
        USER: www-data
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    command: php artisan schedule:work
    volumes:
      - ../laravel:/var/www/html
      - ./laravel.ini:/usr/local/etc/php/conf.d/laravel.ini
    depends_on:
      - redis
      - database
    networks:
      - laravel-network
networks:
  laravel-network:
    driver: bridge